=== tonyfht/jenkins_config/jobs/Proyect_Check/jobs/LifeCicle_IC_No_Pipeline/javadoc/fuentes/NEG_CHECK/src/test/resources/xml/repositorio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.iam.es/repositorio" targetNamespace="http://www.iam.es/repositorio" elementFormDefault="qualified">
	<element name="analisis" type="tns:TipoAnalisis"/>
	<complexType name="TipoAnalisis">
		<sequence>
			<element name="AnalizadorEstaticos" type="tns:Listachequeos"/>
			<element name="AnalizadorRecursos" type="tns:Listachequeos"/>
			<element name="AnalizadorArtefacto" type="tns:Listachequeos"/>
			
			<!--<element name="AnalizadorSubsistemas" type="tns:Listachequeos"/>
        	-->
		</sequence>
	</complexType>
	<complexType name="Listachequeos">
		<sequence>
			<element name="chequeos" type="tns:TipoChequeos" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TipoChequeos">
		<sequence>
			<element name="chequeo" type="tns:TipoChequeo" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="tipo" type="string"/>
	</complexType>
	<complexType name="TipoChequeo">
		<sequence>
			<element name="mensaje" type="tns:TipoMensaje"/>
			<element name="reglas" type="tns:TipoReglas"/>
		</sequence>
		<attribute name="tipo" type="string"/>
		<attribute name="nombre" type="tns:TipoNombreChequeos"/>
		<attribute name="descripcion" type="string"/>
	</complexType>
	<complexType name="TipoReglas">
		<sequence>
			<element name="regla" type="tns:TipoRegla" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TipoRegla">
		<sequence>
			<element name="ejemplo" type="string"/>
			<element name="patronOCadena" type="string"/>
			<element name="tipoComprobacion" type="tns:ValuesTipoComprobacion"/>
			<element name="tratamientoMayusculas" type="tns:ValuesTratamientoMayusculas" minOccurs="0"/>
		</sequence>
		<attribute name="tipo" type="tns:ValuesTipoRegla"/>
	</complexType>
	<complexType name="TipoMensaje">
		<sequence>
			<element name="incorrecto" type="string"/>
			<element name="correcto" type="string"/>
			<element name="avisos" type="string"/>
		</sequence>
	</complexType>
	<simpleType name="ValuesTipoRegla">
		<restriction base="string">
			<enumeration value="ReglaArchivo"/>
			<enumeration value="ReglaContenido"/>
			<enumeration value="ReglaContenidoXML"/>
		</restriction>
	</simpleType>
	<simpleType name="ValuesTipoComprobacion">
		<restriction base="string">
			<enumeration value="EXISTENCIA"/>
			<enumeration value="OBLIGATORIEDAD"/>
			<enumeration value="PROHIBIDO"/>
		</restriction>
	</simpleType>
	<simpleType name="ValuesTratamientoMayusculas">
		<restriction base="string">
			<enumeration value="ESTRICTO"/>
			<enumeration value="IGNORAR"/>
		</restriction>
	</simpleType>
	<simpleType name="ValuesTiposChequeos">
		<restriction base="string">
			<enumeration value="ChequeoContenidoDescriptoresDespliegue"/>
			<enumeration value="ChequeoExistenciaFicheros"/>
			<enumeration value="ChequeoLibreriasDuplicadas"/>
		</restriction>
	</simpleType>
    <simpleType name="TipoNombreChequeos">
		<restriction base="string">
			<enumeration value="ChequeoExtensionArtefacto"/>
			<enumeration value="ChequeosEstructura"/>
			<enumeration value="ChequeosDescriptores"/>
			<enumeration value="ChequeoArchivosNoPermitidosEAR"/>
			<enumeration value="ChequeosFicherosTraza"/>
			<enumeration value="ChequeoLibreriasDuplicadas"/>
			<enumeration value="ChequeosContenidoWebXML"/>
			<enumeration value="ChequeosContenidoApplicationXML"/>
			<enumeration value="ChequeoExtensionEstaticos"/>
			<enumeration value="ChequeoArchivosNoPermitidosEstaticos"/>
			<enumeration value="ChequeoExtensionRecursos"/>
			<enumeration value="ChequeoArchivosNoPermitidosRecursos"/>
			<enumeration value="ChequeoLibreriasNoPermitidas"/>
			
		</restriction>
	</simpleType>
</schema>

=== tonyfht/jenkins_config/jobs/Proyect_Check/jobs/LifeCicle_IC_No_Pipeline/javadoc/fuentes/NEG_CHECK/src/test/resources/xml/Repositorio85.xml
<?xml version="1.0" encoding="UTF-8"?>
<analisis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.iam.es/repositorio repositorio.xsd" xmlns="http://www.iam.es/repositorio">
	<AnalizadorEstaticos>
		<chequeos>
			<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeoExtensionEstaticos" descripcion="Comprobacion de la extenion del archivo de estaticos. La extensión de los archivo de estáticos tiene que ser *.zip ">
				<mensaje>
					<incorrecto>El fichero no tiene la extension adecuada</incorrecto>
					<correcto>El fichero tiene la extension adecuada</correcto>
					<avisos/>
				</mensaje>
				<reglas>
					<regla tipo="ReglaArchivo">
						<ejemplo> .El fichero de estaticos no tiene extensión zip</ejemplo>
						<patronOCadena>.*\.zip</patronOCadena>
						<tipoComprobacion>OBLIGATORIEDAD</tipoComprobacion>
						<tratamientoMayusculas>IGNORAR</tratamientoMayusculas>
					</regla>
				</reglas>
			</chequeo>
			<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeoArchivosNoPermitidosEstaticos" descripcion="Ficheros no permitidos dentro del archivo de estaticos. Estan prohibidos los ficheros: thumbs.db, maven, .maven, .class, .jar, .asp, .java, .svn, .log, .jsp ">
				<mensaje>
					<incorrecto> .Se han encontrado fichero no permitidos</incorrecto>
					<correcto> .No existen ficheros no permitido</correcto>
					<avisos> .Hay un fichero que debe ser revisado</avisos>
				</mensaje>
				<reglas>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero thumbs.db que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\\thumbs\.db</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>IGNORAR</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero maven que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\\maven\\</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo>.Existe un fichero .maven que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.maven</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .class que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.class</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .jar que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.jar</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .asp que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.asp</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .jsp que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.jsp</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .java que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.java</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .svn que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\\\.svn\\</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .log que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.log</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .jsp que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.jsp</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .php que no esta permitido dentro del zip de estaticos</ejemplo>
						<patronOCadena>.*\.php</patronOCadena>
						<tipoComprobacion>EXISTENCIA</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
				</reglas>
			</chequeo>
		</chequeos>
		<chequeos>
	</chequeos>
		<chequeos>
	</chequeos>
	</AnalizadorEstaticos>
	<AnalizadorRecursos>
		<chequeos>
		<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeoExtensionRecursos" descripcion="Comprobacion de la extenion del archivo de recursos. La extensión de los archivo de recursos tiene que ser *.zip">
				<mensaje>
					<incorrecto> .El fichero no tiene la extension adecuada</incorrecto>
					<correcto> . El fichero tiene la extension adecuada</correcto>
					<avisos/>
				</mensaje>
				<reglas>
					<regla tipo="ReglaArchivo">
						<ejemplo> .El fichero de propiedades de recursos no tiene extensión zip</ejemplo>
						<patronOCadena>.*\.zip</patronOCadena>
						<tipoComprobacion>OBLIGATORIEDAD</tipoComprobacion>
						<tratamientoMayusculas>IGNORAR</tratamientoMayusculas>
					</regla>
				</reglas>
			</chequeo>
			<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeoArchivosNoPermitidosRecursos" descripcion="Ficheros no permitidos dentro del archivo de recursos. Estas prohibidos los ficheros: .class, .jar, .asp, .jsp, .java, .svn, .log, ">
				<mensaje>
					<incorrecto> .Se han encontrado fichero no permitidos dentro del archivo de recursos</incorrecto>
					<correcto> .No existen ficheros no permitidos dentro del archivo de recursos</correcto>
					<avisos> .Hay un fichero dentro del archivo de recursos que debe ser revisado</avisos>
				</mensaje>
				<reglas>
				<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .class que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.class</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .jar que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.jar</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .asp que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.asp</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .jsp que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.jsp</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .java que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.java</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .svn que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\\\.svn\\</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					<regla tipo="ReglaArchivo">
						<ejemplo> .Existe un fichero .log que no esta permitido dentro del zip de recursos</ejemplo>
						<patronOCadena>.*\.log</patronOCadena>
						<tipoComprobacion>PROHIBIDO</tipoComprobacion>
						<tratamientoMayusculas>ESTRICTO</tratamientoMayusculas>
					</regla>
					
				</reglas>
			</chequeo>
		</chequeos>
	</AnalizadorRecursos>
	<AnalizadorArtefacto>
	   <chequeos>
			<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeoExtensionArtefacto" descripcion="Comprobacion de la extenion del artefacto desplegable. El archivo de aplicación JEE tiene extensión *.ear">
				<mensaje>
					<incorrecto> .El archivo de aplicación JEE NO tiene extensión .ear</incorrecto>
					<correcto> .El archivo de aplicación JEE tiene extensión .ear</correcto>
					<avisos/>
				</mensaje>
				<reglas>
					<regla tipo="ReglaArchivo">
						<ejemplo> .El archivo de aplicación JEE NO tiene extensión .ear</ejemplo>
						<patronOCadena>.*\.ear</patronOCadena>
						<tipoComprobacion>OBLIGATORIEDAD</tipoComprobacion>
						<tratamientoMayusculas>IGNORAR</tratamientoMayusculas>
					</regla>
				</reglas>
			</chequeo>
			<chequeo tipo="ChequeoExistenciaFicheros" nombre="ChequeosEstructura" descripcion="Comprobacion de la estructura de EAR. Los archivos .ear deben incluir la carpeta META-INF ">
				<mensaje>
					<incorrecto> .Los archivos .ear NO incluyen la carpeta META-INF</incorrecto>
					<correcto> .Los archivos .ear deben incluir la carpeta META-INF</correcto>
					<avisos/>
